### PR TITLE
I sat in skype while you made this whole thing......

### PR DESCRIPTION
**Pull request by Piehthyte**

### CODE REVIEW

**Comment by Technoguyfication** [comment]
Merge />

**Comment by Technoguyfication** [comment]
Merge

**Comment by Technoguyfication** [comment]
Merge

**Comment by Technoguyfication** [comment]
Merge

**Comment by Technoguyfication** [comment]
Merge

**Comment by Technoguyfication** [comment]
No

**Comment by Piehthyte** [comment]
XD Great job :D

**Pull request closed without merging**
